# Site wide configuration

title: Stefan M. Herzog
description:  
  "I am a cognitive-science researcher interested in 
  how to improve people’s judgment and decision making.
  To this end I combine insights from research on  
  heuristics and bounded rationality, wisdom of crowds 
  and machine learning."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: # ?!

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Stefan M. Herzog
  email: herzog@mpib-berlin.mpg.de
  web: http://stefanherzog.org
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: I am a cognitive-science researcher interested in how to improve people’s judgment and decision making.
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
